### PR TITLE
Added win32 support

### PR DESCRIPTION
**Pull request by Mihir-Karbelkar**
Have added a build command to package for windows 32 bit system, tested on dell vostro 1520 (32 bit).

### CODE REVIEW

**Comment by pavlobu** [comment]
Nice! Can this build be performed under x64 architectures?

**Comment by Mihir-Karbelkar** [comment]
I built this on 64 bit linux so should work

**Comment by pavlobu** [comment]
I think it would be great to add that win32 artifact to our Github Actions release pipeline.

The goal is to add this build step in windows platform and copy this produced artifact to our new release
page. This all will be done via Github Actions, we just need to modify our workflow files.

If you know how to do it, I would really appreciate your effort! Otherwise I will deliver your PR
along with that change some time in future.

**Comment by pavlobu** [comment]
Thanks a lot, we will see if artifact builds well with your changes in the next release

**Pull request merged**
