### PR TITLE
typo: encrytpion -> encryption

### PR DESCRIPTION
**Pull request by raboof**
and small punctuation tweaks

### CODE REVIEW

**Comment by pavlobu** [comment]
# [Codecov](https://codecov.io/gh/pavlobu/deskreen/pull/24?src=pr&el=h1) Report
> Merging [#24](https://codecov.io/gh/pavlobu/deskreen/pull/24?src=pr&el=desc) (7e41087) into [master](https://codecov.io/gh/pavlobu/deskreen/commit/ec2e37b35c82197315aeeeefdedc56d42e25eea8?el=desc) (ec2e37b) will **increase** coverage by `59.77%`.
> The diff coverage is `66.56%`.

[Impacted file tree graph](https://codecov.io/gh/pavlobu/deskreen/pull/24?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           master      #24       +/-   ##
===========================================
+ Coverage    4.50%   64.28%   +59.77%     
===========================================
  Files          27      131      +104     
  Lines         466     2139     +1673     
  Branches       41      206      +165     
===========================================
+ Hits           21     1375     +1354     
- Misses        404      628      +224     
- Partials       41      136       +95     
```

| Flag | Coverage Δ | |
|---|---|---|
| unittests | `64.28% <66.56%> (+59.77%)` | :arrow_up: |

Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags#carryforward-flags-in-the-pull-request-comment) to find out more.

| [Impacted Files](https://codecov.io/gh/pavlobu/deskreen/pull/24?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [app/Routes.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL1JvdXRlcy50c3g=) | `0.00% <ø> (ø)` | |
| [app/client/src/App.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvQXBwLnRzeA==) | `0.00% <ø> (-100.00%)` | :arrow_down: |
| [app/client/src/components/ErrorDialog/index.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29tcG9uZW50cy9FcnJvckRpYWxvZy9pbmRleC50c3g=) | `0.00% <0.00%> (ø)` | |
| [...ient/src/components/ToggleDarkModeSwitch/index.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29tcG9uZW50cy9Ub2dnbGVEYXJrTW9kZVN3aXRjaC9pbmRleC50c3g=) | `0.00% <0.00%> (ø)` | |
| [...p/client/src/containers/MainView/changeLanguage.ts](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9jaGFuZ2VMYW5ndWFnZS50cw==) | `0.00% <0.00%> (ø)` | |
| [.../containers/MainView/handleCreatePeerConnection.ts](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9oYW5kbGVDcmVhdGVQZWVyQ29ubmVjdGlvbi50cw==) | `0.00% <0.00%> (ø)` | |
| [...c/containers/MainView/handleNoConnectionTimeout.ts](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9oYW5kbGVOb0Nvbm5lY3Rpb25UaW1lb3V0LnRz) | `0.00% <0.00%> (ø)` | |
| [...inView/handleRemoveDanglingReactRevealContainer.ts](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9oYW5kbGVSZW1vdmVEYW5nbGluZ1JlYWN0UmV2ZWFsQ29udGFpbmVyLnRz) | `0.00% <0.00%> (ø)` | |
| [...t/src/containers/MainView/handleSetVideoQuality.ts](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9oYW5kbGVTZXRWaWRlb1F1YWxpdHkudHM=) | `0.00% <0.00%> (ø)` | |
| [app/client/src/containers/MainView/index.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9pbmRleC50c3g=) | `0.00% <0.00%> (ø)` | |
| ... and [238 more](https://codecov.io/gh/pavlobu/deskreen/pull/24/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/pavlobu/deskreen/pull/24?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/pavlobu/deskreen/pull/24?src=pr&el=footer). Last update [29def23...7e41087](https://codecov.io/gh/pavlobu/deskreen/pull/24?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by pavlobu** [comment]
Hey good catch thanks!

Since if it's a doc fix I'll merge now.
By the way I have fixed those build cache related issues. So next time they should not bother us.

Cheers,
Paul

**Comment by pavlobu** [comment]
Hey good catch thanks!

Sorry right now it is conflicting with previous pull request from other contributor. Please fix it.
Since if it's a doc fix I'll merge it after your fix even if there are builds failing (may happen sometimes due to network issue in github workflows).
By the way I have fixed those build cache related issues. So next time they should not bother us 🎉

Cheers,
Paul

**Comment by raboof** [comment]
> Sorry right now it is conflicting with previous pull request from other contributor. Please fix it.

rebased

**Pull request merged**
