### PR TITLE
[+] Get from Homebrew > README.md

### PR DESCRIPTION
**Pull request by VergeDX**
@pavlobu 
Now we can get YesPlayMusic from [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask) by PR [#99299](https://github.com/Homebrew/homebrew-cask/pull/99299).

### CODE REVIEW

**Comment by pavlobu** [comment]
Hi thanks for adding this!
I have a question, how can I update homebrew binary when new version of deskreen is released?
Do you have a step by step guide on how to do this?

Coz if I add a support for your homebrew cask, then I have no clue how updates will be going there. And I want to automate it and put this procedure in release github workflow: https://github.com/pavlobu/deskreen/blob/master/.github/workflows/release.yml

**Comment by VergeDX** [comment]
@pavlobu 
Docs is here: [Updating a Cask](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask), command: `brew bump-cask-pr --version <new_version> deskreen`.
It will auto-download version <new_version>, and auto make a PR like [Homebrew/homebrew-cask/pull/99313](https://github.com/Homebrew/homebrew-cask/pull/99313).
Also, the command needs a GitHub token named `HOMEBREW_GITHUB_API_TOKEN`, default scoop `gist, public_repo`.
I will try to modify workflows/release.yml.

**Comment by VergeDX** [comment]
@pavlobu 
Seems that's easy to update, I'm glad to try after release v1.0.4.

**Comment by VergeDX** [comment]
@pavlobu 
Still testing, I will open a new PR after I finished.

**Pull request closed without merging**
