### PR TITLE
Fix typo in "trnasformed" on readme.md 

### PR DESCRIPTION
**Pull request by mrjones-plip**
Heya @pavlobu! Good lookin' repo - very likely gonna order a dummy device to try it out.

Until then - I noticed a type in the readme.

### CODE REVIEW

**Comment by pavlobu** [comment]
# [Codecov](https://codecov.io/gh/pavlobu/deskreen/pull/16?src=pr&el=h1) Report
> Merging [#16](https://codecov.io/gh/pavlobu/deskreen/pull/16?src=pr&el=desc) (4025feb) into [master](https://codecov.io/gh/pavlobu/deskreen/commit/ec2e37b35c82197315aeeeefdedc56d42e25eea8?el=desc) (ec2e37b) will **increase** coverage by `59.77%`.
> The diff coverage is `66.56%`.

[Impacted file tree graph](https://codecov.io/gh/pavlobu/deskreen/pull/16?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           master      #16       +/-   ##
===========================================
+ Coverage    4.50%   64.28%   +59.77%     
===========================================
  Files          27      131      +104     
  Lines         466     2139     +1673     
  Branches       41      206      +165     
===========================================
+ Hits           21     1375     +1354     
- Misses        404      628      +224     
- Partials       41      136       +95     
```

| Flag | Coverage Δ | |
|---|---|---|
| unittests | `64.28% <66.56%> (+59.77%)` | :arrow_up: |

Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags#carryforward-flags-in-the-pull-request-comment) to find out more.

| [Impacted Files](https://codecov.io/gh/pavlobu/deskreen/pull/16?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [app/Routes.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL1JvdXRlcy50c3g=) | `0.00% <ø> (ø)` | |
| [app/client/src/App.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvQXBwLnRzeA==) | `0.00% <ø> (-100.00%)` | :arrow_down: |
| [app/client/src/components/ErrorDialog/index.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29tcG9uZW50cy9FcnJvckRpYWxvZy9pbmRleC50c3g=) | `0.00% <0.00%> (ø)` | |
| [...ient/src/components/ToggleDarkModeSwitch/index.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29tcG9uZW50cy9Ub2dnbGVEYXJrTW9kZVN3aXRjaC9pbmRleC50c3g=) | `0.00% <0.00%> (ø)` | |
| [...p/client/src/containers/MainView/changeLanguage.ts](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9jaGFuZ2VMYW5ndWFnZS50cw==) | `0.00% <0.00%> (ø)` | |
| [.../containers/MainView/handleCreatePeerConnection.ts](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9oYW5kbGVDcmVhdGVQZWVyQ29ubmVjdGlvbi50cw==) | `0.00% <0.00%> (ø)` | |
| [...c/containers/MainView/handleNoConnectionTimeout.ts](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9oYW5kbGVOb0Nvbm5lY3Rpb25UaW1lb3V0LnRz) | `0.00% <0.00%> (ø)` | |
| [...inView/handleRemoveDanglingReactRevealContainer.ts](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9oYW5kbGVSZW1vdmVEYW5nbGluZ1JlYWN0UmV2ZWFsQ29udGFpbmVyLnRz) | `0.00% <0.00%> (ø)` | |
| [...t/src/containers/MainView/handleSetVideoQuality.ts](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9oYW5kbGVTZXRWaWRlb1F1YWxpdHkudHM=) | `0.00% <0.00%> (ø)` | |
| [app/client/src/containers/MainView/index.tsx](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree#diff-YXBwL2NsaWVudC9zcmMvY29udGFpbmVycy9NYWluVmlldy9pbmRleC50c3g=) | `0.00% <0.00%> (ø)` | |
| ... and [238 more](https://codecov.io/gh/pavlobu/deskreen/pull/16/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/pavlobu/deskreen/pull/16?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/pavlobu/deskreen/pull/16?src=pr&el=footer). Last update [30595cf...4025feb](https://codecov.io/gh/pavlobu/deskreen/pull/16?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by pavlobu** [comment]
Hi thank you for submitting it!

There are some failing checks related to concurrent github workflows running. Let me fix that and I'll merge it

**Comment by mrjones-plip** [comment]
As well, I'm happy to merge master back to my branch and repush if that's easier!

**Comment by pavlobu** [comment]
Hi. It's late night by my side now. The problem is with two concurrent github workflow jobs running, I'm using a third party action for caching with is basically wirten to generate same keyname for cuncurrent jobs running. I'll try tomorrow to replace with native cache code and give diffenet key names for codecov and linux test builds.

for now I can give you a link on what I found. How to make 'native' caching, note, it is different for mac/ubuntu and windows:
https://github.com/actions/cache/blob/9ab95382c899bf0953a0c6c1374373fc40456ffe/examples.md#node---npm

thanks!

**Comment by mrjones-plip** [comment]
heh - I think I'll wait and see if I start doing actual development on this project before learning your CI stack. Hopefully it's helpful to fix the concurrent workflows issue, but otherwise, absolutely no rush on my side! Take a day or a month ;)

**Comment by pavlobu** [comment]
alright I've fixed build issues. But yarn install may fail sometimes because there is network issue.

but for now it is just a simple typo fix after all, so from now on if pull requests are related to documentation fixes, then I'll just simply merge even if it fails.

fill dive deeper on how to get rid of those network problems during builds. Maybe need to switch to other npm registry dynamically? Still don't know.

Cheers,
Paul

**Pull request merged**
