### PR TITLE
Added German translation

### PR DESCRIPTION
**Pull request by Aceto1**
* add german translation
* resolved conflicts
These might not be the most idiomatic but I think they're understandable. Still might have to work on some of them in the future.

### CODE REVIEW

**Comment by pavlobu** [comment]
Hi @Aceto1 
Thank you for your work. Please be aware as I informed in https://github.com/pavlobu/deskreen/issues/60
https://github.com/pavlobu/deskreen/issues/60#issuecomment-782901641


That my friend is already translating a website to German. He is not a native speaker so your check will be good. I'llshare his app translation here so you can also have a look if its ok or adjust some of your translations

Cheers,
Paul

**Comment by pavlobu** [comment]
Here is his App translations for. You can check if they are ok or if you have mistakes you can correct them and submit here.
He will be finishing website translations to German soon and I will create a separate branch with them here:
https://github.com/Deskreen/deskreen-website-locales
I will let you know when it is ready, so you can have a check and maybe submit your fixes in pull request there.

BTW I fixed those builds problems on master, you can rebase to use them.

Cheers,
Paul

**Comment by Aceto1** [comment]
Did you mean to link to his fork by chance? Otherwise I'm not sure where to find them right now 😅

**Comment by pavlobu** [comment]
> Did you mean to link to his fork by chance? Otherwise I'm not sure where to find them right now 😅

sorry I thought I have sent a link. Here is a link to google drive:
https://drive.google.com/drive/folders/17wjTO_VP1ou_CaALgXJRGabfgNs489pV?usp=sharing

He is not a developer, he just helped with tranlsations

**Comment by pavlobu** [comment]
Ok German added in new release 1.0.11
thank you very much for your work!

Website translations for german are here:
https://github.com/Deskreen/deskreen-website-locales

if you find any typo you can submit your PR there.

I'll be closing this request as your changes are added in separate PR along with other changes

Thank you very much for your work @Aceto1 !

**Pull request closed without merging**
