### PR TITLE
Create it  translation.json

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by NicKoehler** [comment]
I pushed full italian translations in pr #150, if you want to check mine so you don't have to make the work that's already been done

**Comment by albanobattistella** [comment]
Perfect! Thanks!
________________________________
Da: NicKoehler ***@***.***>
Inviato: venerdì 18 giugno 2021 09:29
A: pavlobu/deskreen ***@***.***>
Cc: albanobattistella ***@***.***>; Author ***@***.***>
Oggetto: Re: [pavlobu/deskreen] Create it translation.json (#151)


I pushed full italian translations in pr #150<https://github.com/pavlobu/deskreen/pull/150>, if you want to check mine so you don't have to make the work that's already been done

**Comment by pavlobu** [comment]
great news @NicKoehler, thanks!

if you have free time, please add translations for Deskreen website here:
https://github.com/Deskreen/deskreen-website-locales

we decided to add translations for app along with website so it will be fair for that language community.
For now I will wait until website translations are done

**Comment by pavlobu** [comment]
thank you very much! Italian is added in this PR:
https://github.com/pavlobu/deskreen/pull/196

**Pull request closed without merging**
