### PR TITLE
Added initial Dutch language support

### PR DESCRIPTION
**Pull request by sebastianschauenburg**
Tried to keep the Capital Letter usage the same as with the English version. Unfortunately I'm not a NPM coder, so I couldn't run the yarn tests. Let me know if you can merge this or what needs to be done to get it into a proper state.

### CODE REVIEW

**Comment by pavlobu** [comment]
@sebastianschauenburg outstanding! Thank you for your work!
I'm in progress of finishing a template for a website. I'll be updating you soon

**Comment by pavlobu** [comment]
sees that you need to update snapshots, the instructions are in docs :
https://github.com/pavlobu/deskreen#how-to-regenerate-snapshots-if-you-have-tests-failing-when-running-yarn-test

then pls make sure `yarn test-all` does not fail on your local environment before pushing a chagne
Thanks!

**Comment by pavlobu** [comment]
still snapshots are failing. I can give you a hand with that. It's quite late by my side

**Comment by sebastianschauenburg** [comment]
Please remove this pull request. Will open a new one in a minute.

**Pull request closed without merging**
