### PR TITLE
Added Danish Translation

### PR DESCRIPTION
**Pull request by LauritsLL**

### CODE REVIEW

**Comment by pavlobu** [comment]
@LauritsLL thank you very much for your work! 🙏
Those builds are failing because I have some new code added that I need to clean up... I should have created a separate branch for FPS counter...

With app translations we also need to have a website translations:
https://github.com/Deskreen/deskreen-website-locales
as we discussed earlier in this thread:
https://github.com/pavlobu/deskreen/issues/60

chan you also help with websites translations? they provide useful info for users with Howtos and FAQs.
I will wait with merging this pull request until we have a website transaltion for Danish language as well.

Thank you for your work @LauritsLL !
Paul

**Comment by LauritsLL** [comment]
> @LauritsLL thank you very much for your work! 🙏
> Those builds are failing because I have some new code added that I need to clean up... I should have created a separate branch for FPS counter...
> 
> With app translations we also need to have a website translations:
> https://github.com/Deskreen/deskreen-website-locales
> as we discussed earlier in this thread:
> #60
> 
> chan you also help with websites translations? they provide useful info for users with Howtos and FAQs.
> I will wait with merging this pull request until we have a website transaltion for Danish language as well.
> 
> Thank you for your work @LauritsLL !
> Paul

Of course! I will do it soon. 😄 

/Laurits

**Comment by LauritsLL** [comment]
I have now added Danish translation for the website - here is the pull request: [#6](https://github.com/Deskreen/deskreen-website-locales/pull/6)
I hope it's okay. :)

/Laurits

**Comment by pavlobu** [comment]
@LauritsLL thank you very much for your work!! I'll have a look and if it is ok, I'll merge.

Also I'll fix test issues that we have in this build

**Comment by pavlobu** [comment]
Ok Danish added in new release 1.0.11
thank you very much for your work!

I'll be closing this request as your changes are added in separate PR along with other changes

Thank you very much for your work @LauritsLL !

**Comment by LauritsLL** [comment]
@pavlobu I was glad that I could be of any help to this amazing project of yours!

/Laurits

**Pull request closed without merging**
