### PR TITLE
Create it translations

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by pavlobu** [comment]
hey, good start there is 7 commits in this bull request, it can be squashed into one. Thanks!

**Comment by pavlobu** [comment]
if you are new to git, then I may help you with squashing... But it will be nice if you can make it. Thanks!

**Comment by filiptronicek** [comment]
Hey @pavlobu, wouldn't it be easier to just squash and merge this pull request?

**Comment by pavlobu** [comment]
Hi @taotieren @filiptronicek,
I finished with adding all necessary translations for the current app version as well as some upcoming features translations too.
You can get started with translations here:
https://github.com/pavlobu/deskreen#get-started-for-translators

Currently there is no guidance for adding translations for a website, but I will be adding it really soon and I will update you on that.For now, you can start with app translations if you want
The instructions are friendly both for coders and non-coders.

Looking forward for your input,
Paul

**Comment by pavlobu** [comment]
> Hey @pavlobu, wouldn't it be easier to just squash and merge this pull request?

Hi.
I meant the same here: https://github.com/pavlobu/deskreen/pull/76#issuecomment-769963445

I can't squash @albanobattistella commits. It should be done by @albanobattistella who submitted the PR request

**Comment by pavlobu** [comment]
Hi @albanobattistella 

There is a guy Roberto, who emailed me not so far and offering his help on adding translation for Italian.
roberto.marianantoni@gmail.com
You can email him so you can split your tasks.

Cheers,
Paul

**Comment by pavlobu** [comment]
Hi @albanobattistella 

I finally finished language templates for Deskreen website.

Here are the guides on how to add a new language for Deskreen Website
https://github.com/Deskreen/deskreen-website-locales

Thank you in advance!
Paul

**Comment by pavlobu** [comment]
I'll close this pull request for now, since there is no activity here for a while.

**Pull request closed without merging**
