### PR TITLE
[F] Fix GitHub Actions trigger issues.

### PR DESCRIPTION
**Pull request by VergeDX**
@pavlobu 
I move previous homebrew-pr actions to another action, the trigger condition is "on released".
I hope it can fix the previous mistake...

### CODE REVIEW

**Comment by VergeDX** [comment]
Wait, What is ${GITHUB_REF##*/} after released...? Let me test.

**Comment by pavlobu** [comment]
> Wait, What is ${GITHUB_REF##*/} after released...? Let me test.

lats time when I did Re-run all jobs it did fine with that syntax:
https://github.com/pavlobu/deskreen/runs/1850557736?check_suite_focus=true

**Comment by VergeDX** [comment]
Behavior not change, think that's right.
I just testing on a empty repo [VergeDX/Test_GitHub_Actions](https://github.com/VergeDX/Test_GitHub_Actions).

**Comment by pavlobu** [comment]
@VergeDX thank you very much! merging 🎉

**Comment by VergeDX** [comment]
<3

**Comment by pavlobu** [comment]
Hi @VergeDX 
When I released v1.0.6 there were some problems while during your homebrew task:
https://github.com/pavlobu/deskreen/runs/1942855611?check_suite_focus=true#step:4:210

do you happen to know what went wrong?
Cheers

**Comment by VergeDX** [comment]
@pavlobu 
Same issues in [Homebrew/discussions](https://github.com/Homebrew/discussions/discussions/758), maybe you can try answer of [StackOverflow](https://stackoverflow.com/questions/64059610/how-to-resolve-refusing-to-allow-an-oauth-app-to-create-or-update-workflow-on)...?

**Comment by VergeDX** [comment]
@pavlobu Oh, I know what's wrong!  
See [Homebrew/brew/pull/10568](https://github.com/Homebrew/brew/pull/10568), now HOMEBREW_GITHUB_API_TOKEN need a extra permission "workflow".  
I will PR fixes now, please delete the old Homebrew token, add new token by open this link:  
[https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew](https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew)

**Pull request merged**
