### PR TITLE
Correct spelling mistakes

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by pavlobu** [comment]
Hi thanks for your work! Right now some tests are failing, please fix tests -> squash -> and force push to your branch

how to run tests instructions are in README.md

Cheers,
Paul

**Comment by EdwardBetts** [comment]
I've fixed the commit so the tests pass.

**Comment by pavlobu** [comment]
Amazing work! Merged

**Comment by pavlobu** [comment]
Thank you very much!

**Comment by pavlobu** [comment]
Thanks again. I made a new release:

https://github.com/pavlobu/deskreen/releases/tag/v1.0.1

**Comment by EdwardBetts** [comment]
Happy to be of service. Sorry I missed incorrect spelling of Deskreen in the error dialog.

I found most of the spelling mistakes using software tool called codespell.

https://github.com/codespell-project/codespell/

Codespell uses a dictionary of 30,000 common spelling mistakes. It can't know that Descreen is incorrect.

Thanks for making deskreen, it is very impressive software.

**Comment by pavlobu** [comment]
> I found most of the spelling mistakes using software tool called codespell.
> 
> https://github.com/codespell-project/codespell/
> 
> Codespell uses a dictionary of 30,000 common spelling mistakes. It can't know that Descreen is incorrect.

Thank you for sharing it! This is a very useful tool.

**Comment by pavlobu** [comment]
There is actually extension for vscode: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
very useful, since I use vscode for development.

using it from now on

**Pull request merged**
