### PR TITLE
Upgrade electron to V13 / Enable Pipewire v0.3 support

### PR DESCRIPTION
**Pull request by seffs**
Following #140 , upgrade electron in order to support pipewire>=0.3 by default.

Users of xdg-desktop-portal>=1.10  beware: [Multiple dialogs may show up, or just a black screen](https://github.com/electron/electron/issues/31588#issuecomment-1007294540). Try running as follow:

` XDG_SESSION_TYPE=wayland2 deskreen --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer`

### CODE REVIEW

**Comment by artogahr** [comment]
Works fine on Arch Linux with Gnome 42 Wayland.

ran as: `./Deskreen-1.0.13.AppImage --enable-features=WebRTCPipeWireCapturer`

**Comment by pavlobu** [comment]
This is awesome, thanks! I will get back to it as soon as I get to safe place. There is a war in my country now. I live in Ukraine

**Comment by RafayAK** [comment]
@seffs I see you first tried to upgrade Electorn to V18 and then reverted back to V13, was there something wrong with the build process?

**Comment by seffs** [comment]
@RafayAK there is a breaking change starting in V14 regarding the `remote` module as detailed [here](https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-140). I (_really_) tried to update the relevant parts, but ran out of time and energy. I had no problems compiling it however. The result was a blank screen in the app, probably related to the broken routing.

@pavlobu might have an idea of what is going on there, since I am not a web dev and won't be investing more time into it. It just works on my machine right now, and hopefully for anyone else using wayland. Stay strong!

**Comment by RafayAK** [comment]
@seffs Thanks a lot. I'll see if I can build upon your work

**Comment by theofficialgman** [comment]
This PR merging would be an immediate improvement (even if only v13). electron versions less than this are not compatible with many new OSs due to https://github.com/electron/electron/pull/31091

**Comment by pavlobu** [comment]
Ok so I've tried this PR and I've noticed a performance glitch every second. 
I did some debugging and noticed that it is because of a 1 second interval that checks network status.
That is weird. I don't know why this didn't happen on older electron versions.

I'm currently trying to upgrade to electron 18 and I found that unfortunately, since I'm heavily depending on 'remote.getGlobal', it is the main root cause of a white screen in descreen app.
The point is, should have not used rely on 'remote' module from the very beginning.

So i've commented all places where I used it in on or another way and finally the react UI was loaded successfully. But I need to refactor a bunch of app files to make everything work as before.

Now the only solution I see to get rid of 'remote' module of electron, is to find all the places where I'm using it and switch to using ipcRenderer.invoke
And that is a lot of work. So I'll be digging into it in the following moths. Stay tuned for a huge electron version bump guys!

**Comment by pavlobu** [comment]
here is a branch where I'm tinkering with an electron version bump:

`try-to-bump-to-electron-18`

**Comment by pavlobu** [comment]
Ok now your changes are in master.

Thanks again!

I made a huge electron version bump to electron v18.2.3
you may try to download and see if it solves your previous problem.

**Comment by theofficialgman** [comment]
> Ok now your changes are in master.
> 
> Thanks again!
> 
> I made a huge electron version bump to electron v18.2.3 you may try to download and see if it solves your previous problem.

@pavlobu please bump to 18.2.4 or greater. 18.0.0-18.2.3 have a bug causing it to not run on buster/bionic and older distros

**Comment by pavlobu** [comment]
@theofficialgman, ok bumped to latest stable `v19.0.0` as it marked [here](https://www.electronjs.org/releases/stable)
Release can be downloaded from here:
[v2.0.1](https://github.com/pavlobu/deskreen/releases/tag/v2.0.1)

**Comment by theofficialgman** [comment]
@pavlobu sorry don't use v19.x.y... it's broken on buster/bionic. Every day, a new electron bug. https://github.com/electron/electron/issues/34399

**Comment by pavlobu** [comment]
🤔

**Comment by pavlobu** [comment]
it's ok I will downgrade in next release with language changes, which will come today or tomorrow, I just don't want to annoy users with too many updates in one day

**Comment by theofficialgman** [comment]
@pavlobu 19.x.y is considered stable now... it just really isn't "stable" because it just released a few days ago and has some problematic bugs

if you want, you can just put ```electron": "^18.2.4",``` in your packages file. that will grab the latest 18.x.y bugfix release. the latest on that branch is 18.3.1 and they will continue to do bugfixes and CVE backports for a while longer.

**Comment by pavlobu** [comment]
Nice, I will pull 18.2.4 then and will stay on 18.x.x stable releases while they are "stabilizing" 19.x.x versions ;)

**Comment by artogahr** [comment]
@Elkingahmed please consider deleting these comments, they contribute nothing and are too long, making them spam

**Pull request merged**
