### PR TITLE
[+] Auto update Homebrew cask from GitHub Actions.

### PR DESCRIPTION
**Pull request by VergeDX**
@pavlobu 
I finished GitHub Action to auto-update the Deskreen cask.
It will auto-create PR to Homebrew-cask repo, like [homebrew-cask/pull/99386](https://github.com/Homebrew/homebrew-cask/pull/99386).
But please noticed comment at [.github/workflows/release.yml#L136](https://github.com/VergeDX/deskreen/blob/master/.github/workflows/release.yml#L136), you need to create a personal access token.

### CODE REVIEW

**Comment by pavlobu** [comment]
@VergeDX 
Fantastic!
That is a great improvement you made.

I have added a GitHub secret for HOMEBREW_GITHUB_API_TOKEN
following your instructions. I hope it will work during next release.

Merging now.

Thank you again,
Paul

**Comment by VergeDX** [comment]
@pavlobu 
I hope it will work too : )

**Comment by pavlobu** [comment]
@VergeDX
Hi, your homebrew job is failing on new release. The problem is it is trying to fetch the file that is not built and released yet

https://github.com/pavlobu/deskreen/runs/1850451037?check_suite_focus=true

**Comment by pavlobu** [comment]
We need to find out how to trigger your job Only after when I click Create Release button. Because now the job is doing Draft of release, without publishing it yet. Then I write changelog for release and finally click Create release button in Draft release.


so there should be a way to trigger your homebrew job when I hit Create release button. do you happen to know if there is such a mechanism already built in in github workflows?

**Comment by pavlobu** [comment]
Or maybe there is a way to manually trigger your job? can you teach me how? 

I still think it is better to make it automated..

**Comment by pavlobu** [comment]
right now the solution for me was to re-run all jobs when new release is built and published. so I need to do it manually then I need to remove new unnecessary draft release. so its manual process and inconvenient.

**Comment by pavlobu** [comment]
i guess for that we can use this:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release

and for your homebrew and uploading changes to other package managers we can create a separate workflow and call it something like: 'post-release-publish' or something like that.
and what it will do is it will have different jobs for each package manager and it will execute those jobs after I hit that Create release button. It will have access to new files and all will go smooth.

**Comment by VergeDX** [comment]
@pavlobu 
I'm sorry about that : (, it seems that this is caused by my lack of understanding of workflow...
I think after [the release step](https://github.com/pavlobu/deskreen/blob/master/.github/workflows/release.yml#L26), the file will exist. But I'm wrong : (.
It warns me to discuss first, then opens PR...
I originally planned to use a ready-made workflow, but not meet the requirements.
I will try to fix it now!

**Comment by pavlobu** [comment]
No problem mate. Technology is so vast already and keeps getting more complex every moment. We always need to keep learning and it will be mo problem. A failure is just a smalle lesson that you need an adjustment to do better :)

**Pull request merged**
